# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import wpath
from scripts.pb.logic import ext_pb2 as logic_dot_ext__pb2


class LogicExtStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDevice = channel.unary_unary(
                '/pb.LogicExt/RegisterDevice',
                request_serializer=logic_dot_ext__pb2.RegisterDeviceReq.SerializeToString,
                response_deserializer=logic_dot_ext__pb2.RegisterDeviceResp.FromString,
                )
        self.SendMessage = channel.unary_unary(
                '/pb.LogicExt/SendMessage',
                request_serializer=logic_dot_ext__pb2.SendMessageReq.SerializeToString,
                response_deserializer=logic_dot_ext__pb2.SendMessageResp.FromString,
                )
        self.AddFriend = channel.unary_unary(
                '/pb.LogicExt/AddFriend',
                request_serializer=logic_dot_ext__pb2.AddFriendReq.SerializeToString,
                response_deserializer=logic_dot_ext__pb2.AddFriendResp.FromString,
                )
        self.AgreeAddFriend = channel.unary_unary(
                '/pb.LogicExt/AgreeAddFriend',
                request_serializer=logic_dot_ext__pb2.AgreeAddFriendReq.SerializeToString,
                response_deserializer=logic_dot_ext__pb2.AgreeAddFriendResp.FromString,
                )
        self.SetFriend = channel.unary_unary(
                '/pb.LogicExt/SetFriend',
                request_serializer=logic_dot_ext__pb2.SetFriendReq.SerializeToString,
                response_deserializer=logic_dot_ext__pb2.SetFriendResp.FromString,
                )
        self.GetFriends = channel.unary_unary(
                '/pb.LogicExt/GetFriends',
                request_serializer=logic_dot_ext__pb2.GetFriendsReq.SerializeToString,
                response_deserializer=logic_dot_ext__pb2.GetFriendsResp.FromString,
                )
        self.CreateGroup = channel.unary_unary(
                '/pb.LogicExt/CreateGroup',
                request_serializer=logic_dot_ext__pb2.CreateGroupReq.SerializeToString,
                response_deserializer=logic_dot_ext__pb2.CreateGroupResp.FromString,
                )
        self.UpdateGroup = channel.unary_unary(
                '/pb.LogicExt/UpdateGroup',
                request_serializer=logic_dot_ext__pb2.UpdateGroupReq.SerializeToString,
                response_deserializer=logic_dot_ext__pb2.UpdateGroupResp.FromString,
                )
        self.GetGroup = channel.unary_unary(
                '/pb.LogicExt/GetGroup',
                request_serializer=logic_dot_ext__pb2.GetGroupReq.SerializeToString,
                response_deserializer=logic_dot_ext__pb2.GetGroupResp.FromString,
                )
        self.GetGroups = channel.unary_unary(
                '/pb.LogicExt/GetGroups',
                request_serializer=logic_dot_ext__pb2.GetGroupsReq.SerializeToString,
                response_deserializer=logic_dot_ext__pb2.GetGroupsResp.FromString,
                )
        self.AddGroupMembers = channel.unary_unary(
                '/pb.LogicExt/AddGroupMembers',
                request_serializer=logic_dot_ext__pb2.AddGroupMembersReq.SerializeToString,
                response_deserializer=logic_dot_ext__pb2.AddGroupMembersResp.FromString,
                )
        self.UpdateGroupMember = channel.unary_unary(
                '/pb.LogicExt/UpdateGroupMember',
                request_serializer=logic_dot_ext__pb2.UpdateGroupMemberReq.SerializeToString,
                response_deserializer=logic_dot_ext__pb2.UpdateGroupMemberResp.FromString,
                )
        self.DeleteGroupMember = channel.unary_unary(
                '/pb.LogicExt/DeleteGroupMember',
                request_serializer=logic_dot_ext__pb2.DeleteGroupMemberReq.SerializeToString,
                response_deserializer=logic_dot_ext__pb2.DeleteGroupMemberResp.FromString,
                )
        self.GetGroupMembers = channel.unary_unary(
                '/pb.LogicExt/GetGroupMembers',
                request_serializer=logic_dot_ext__pb2.GetGroupMembersReq.SerializeToString,
                response_deserializer=logic_dot_ext__pb2.GetGroupMembersResp.FromString,
                )


class LogicExtServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterDevice(self, request, context):
        """注册设备
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """发送消息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFriend(self, request, context):
        """添加好友
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgreeAddFriend(self, request, context):
        """同意添加好友
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFriend(self, request, context):
        """设置好友信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFriends(self, request, context):
        """获取好友列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGroup(self, request, context):
        """创建群组
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGroup(self, request, context):
        """更新群组
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroup(self, request, context):
        """获取群组信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroups(self, request, context):
        """获取用户加入的所有群组
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddGroupMembers(self, request, context):
        """添加群组成员
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGroupMember(self, request, context):
        """更新群组成员信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteGroupMember(self, request, context):
        """添加群组成员
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupMembers(self, request, context):
        """获取群组成员
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogicExtServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDevice,
                    request_deserializer=logic_dot_ext__pb2.RegisterDeviceReq.FromString,
                    response_serializer=logic_dot_ext__pb2.RegisterDeviceResp.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=logic_dot_ext__pb2.SendMessageReq.FromString,
                    response_serializer=logic_dot_ext__pb2.SendMessageResp.SerializeToString,
            ),
            'AddFriend': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFriend,
                    request_deserializer=logic_dot_ext__pb2.AddFriendReq.FromString,
                    response_serializer=logic_dot_ext__pb2.AddFriendResp.SerializeToString,
            ),
            'AgreeAddFriend': grpc.unary_unary_rpc_method_handler(
                    servicer.AgreeAddFriend,
                    request_deserializer=logic_dot_ext__pb2.AgreeAddFriendReq.FromString,
                    response_serializer=logic_dot_ext__pb2.AgreeAddFriendResp.SerializeToString,
            ),
            'SetFriend': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFriend,
                    request_deserializer=logic_dot_ext__pb2.SetFriendReq.FromString,
                    response_serializer=logic_dot_ext__pb2.SetFriendResp.SerializeToString,
            ),
            'GetFriends': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFriends,
                    request_deserializer=logic_dot_ext__pb2.GetFriendsReq.FromString,
                    response_serializer=logic_dot_ext__pb2.GetFriendsResp.SerializeToString,
            ),
            'CreateGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroup,
                    request_deserializer=logic_dot_ext__pb2.CreateGroupReq.FromString,
                    response_serializer=logic_dot_ext__pb2.CreateGroupResp.SerializeToString,
            ),
            'UpdateGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGroup,
                    request_deserializer=logic_dot_ext__pb2.UpdateGroupReq.FromString,
                    response_serializer=logic_dot_ext__pb2.UpdateGroupResp.SerializeToString,
            ),
            'GetGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroup,
                    request_deserializer=logic_dot_ext__pb2.GetGroupReq.FromString,
                    response_serializer=logic_dot_ext__pb2.GetGroupResp.SerializeToString,
            ),
            'GetGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroups,
                    request_deserializer=logic_dot_ext__pb2.GetGroupsReq.FromString,
                    response_serializer=logic_dot_ext__pb2.GetGroupsResp.SerializeToString,
            ),
            'AddGroupMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.AddGroupMembers,
                    request_deserializer=logic_dot_ext__pb2.AddGroupMembersReq.FromString,
                    response_serializer=logic_dot_ext__pb2.AddGroupMembersResp.SerializeToString,
            ),
            'UpdateGroupMember': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGroupMember,
                    request_deserializer=logic_dot_ext__pb2.UpdateGroupMemberReq.FromString,
                    response_serializer=logic_dot_ext__pb2.UpdateGroupMemberResp.SerializeToString,
            ),
            'DeleteGroupMember': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteGroupMember,
                    request_deserializer=logic_dot_ext__pb2.DeleteGroupMemberReq.FromString,
                    response_serializer=logic_dot_ext__pb2.DeleteGroupMemberResp.SerializeToString,
            ),
            'GetGroupMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupMembers,
                    request_deserializer=logic_dot_ext__pb2.GetGroupMembersReq.FromString,
                    response_serializer=logic_dot_ext__pb2.GetGroupMembersResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.LogicExt', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LogicExt(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LogicExt/RegisterDevice',
            logic_dot_ext__pb2.RegisterDeviceReq.SerializeToString,
            logic_dot_ext__pb2.RegisterDeviceResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LogicExt/SendMessage',
            logic_dot_ext__pb2.SendMessageReq.SerializeToString,
            logic_dot_ext__pb2.SendMessageResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddFriend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LogicExt/AddFriend',
            logic_dot_ext__pb2.AddFriendReq.SerializeToString,
            logic_dot_ext__pb2.AddFriendResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AgreeAddFriend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LogicExt/AgreeAddFriend',
            logic_dot_ext__pb2.AgreeAddFriendReq.SerializeToString,
            logic_dot_ext__pb2.AgreeAddFriendResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetFriend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LogicExt/SetFriend',
            logic_dot_ext__pb2.SetFriendReq.SerializeToString,
            logic_dot_ext__pb2.SetFriendResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFriends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LogicExt/GetFriends',
            logic_dot_ext__pb2.GetFriendsReq.SerializeToString,
            logic_dot_ext__pb2.GetFriendsResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LogicExt/CreateGroup',
            logic_dot_ext__pb2.CreateGroupReq.SerializeToString,
            logic_dot_ext__pb2.CreateGroupResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LogicExt/UpdateGroup',
            logic_dot_ext__pb2.UpdateGroupReq.SerializeToString,
            logic_dot_ext__pb2.UpdateGroupResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LogicExt/GetGroup',
            logic_dot_ext__pb2.GetGroupReq.SerializeToString,
            logic_dot_ext__pb2.GetGroupResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LogicExt/GetGroups',
            logic_dot_ext__pb2.GetGroupsReq.SerializeToString,
            logic_dot_ext__pb2.GetGroupsResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddGroupMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LogicExt/AddGroupMembers',
            logic_dot_ext__pb2.AddGroupMembersReq.SerializeToString,
            logic_dot_ext__pb2.AddGroupMembersResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateGroupMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LogicExt/UpdateGroupMember',
            logic_dot_ext__pb2.UpdateGroupMemberReq.SerializeToString,
            logic_dot_ext__pb2.UpdateGroupMemberResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteGroupMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LogicExt/DeleteGroupMember',
            logic_dot_ext__pb2.DeleteGroupMemberReq.SerializeToString,
            logic_dot_ext__pb2.DeleteGroupMemberResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGroupMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.LogicExt/GetGroupMembers',
            logic_dot_ext__pb2.GetGroupMembersReq.SerializeToString,
            logic_dot_ext__pb2.GetGroupMembersResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
