# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: push.ext.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from logic import ext_pb2 as logic_dot_ext__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='push.ext.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0epush.ext.proto\x12\x02pb\x1a\x0flogic.ext.proto\"]\n\rAddFriendPush\x12\x11\n\tfriend_id\x18\x01 \x01(\x03\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x12\n\navatar_url\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"M\n\x12\x41greeAddFriendPush\x12\x11\n\tfriend_id\x18\x01 \x01(\x03\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x12\n\navatar_url\x18\x03 \x01(\t\"z\n\x0fUpdateGroupPush\x12\x0e\n\x06opt_id\x18\x01 \x01(\x03\x12\x10\n\x08opt_name\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\navatar_url\x18\x04 \x01(\t\x12\x14\n\x0cintroduction\x18\x05 \x01(\t\x12\r\n\x05\x65xtra\x18\x06 \x01(\t\"Y\n\x13\x41\x64\x64GroupMembersPush\x12\x0e\n\x06opt_id\x18\x01 \x01(\x03\x12\x10\n\x08opt_name\x18\x02 \x01(\t\x12 \n\x07members\x18\x03 \x03(\x0b\x32\x0f.pb.GroupMember\"R\n\x15RemoveGroupMemberPush\x12\x0e\n\x06opt_id\x18\x01 \x01(\x03\x12\x10\n\x08opt_name\x18\x02 \x01(\t\x12\x17\n\x0f\x64\x65leted_user_id\x18\x03 \x01(\x03*\x95\x01\n\x08PushCode\x12\x12\n\x0ePC_ADD_DEFAULT\x10\x00\x12\x11\n\rPC_ADD_FRIEND\x10\x64\x12\x17\n\x13PC_AGREE_ADD_FRIEND\x10\x65\x12\x13\n\x0fPC_UPDATE_GROUP\x10n\x12\x18\n\x14PC_ADD_GROUP_MEMBERS\x10x\x12\x1a\n\x16PC_REMOVE_GROUP_MEMBER\x10yb\x06proto3'
  ,
  dependencies=[logic_dot_ext__pb2.DESCRIPTOR,])

_PUSHCODE = _descriptor.EnumDescriptor(
  name='PushCode',
  full_name='pb.PushCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PC_ADD_DEFAULT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PC_ADD_FRIEND', index=1, number=100,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PC_AGREE_ADD_FRIEND', index=2, number=101,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PC_UPDATE_GROUP', index=3, number=110,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PC_ADD_GROUP_MEMBERS', index=4, number=120,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PC_REMOVE_GROUP_MEMBER', index=5, number=121,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=513,
  serialized_end=662,
)
_sym_db.RegisterEnumDescriptor(_PUSHCODE)

PushCode = enum_type_wrapper.EnumTypeWrapper(_PUSHCODE)
PC_ADD_DEFAULT = 0
PC_ADD_FRIEND = 100
PC_AGREE_ADD_FRIEND = 101
PC_UPDATE_GROUP = 110
PC_ADD_GROUP_MEMBERS = 120
PC_REMOVE_GROUP_MEMBER = 121



_ADDFRIENDPUSH = _descriptor.Descriptor(
  name='AddFriendPush',
  full_name='pb.AddFriendPush',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='friend_id', full_name='pb.AddFriendPush.friend_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='pb.AddFriendPush.nickname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='avatar_url', full_name='pb.AddFriendPush.avatar_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='pb.AddFriendPush.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=132,
)


_AGREEADDFRIENDPUSH = _descriptor.Descriptor(
  name='AgreeAddFriendPush',
  full_name='pb.AgreeAddFriendPush',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='friend_id', full_name='pb.AgreeAddFriendPush.friend_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='pb.AgreeAddFriendPush.nickname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='avatar_url', full_name='pb.AgreeAddFriendPush.avatar_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=211,
)


_UPDATEGROUPPUSH = _descriptor.Descriptor(
  name='UpdateGroupPush',
  full_name='pb.UpdateGroupPush',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='opt_id', full_name='pb.UpdateGroupPush.opt_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opt_name', full_name='pb.UpdateGroupPush.opt_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='pb.UpdateGroupPush.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='avatar_url', full_name='pb.UpdateGroupPush.avatar_url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='introduction', full_name='pb.UpdateGroupPush.introduction', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extra', full_name='pb.UpdateGroupPush.extra', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=335,
)


_ADDGROUPMEMBERSPUSH = _descriptor.Descriptor(
  name='AddGroupMembersPush',
  full_name='pb.AddGroupMembersPush',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='opt_id', full_name='pb.AddGroupMembersPush.opt_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opt_name', full_name='pb.AddGroupMembersPush.opt_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='members', full_name='pb.AddGroupMembersPush.members', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=426,
)


_REMOVEGROUPMEMBERPUSH = _descriptor.Descriptor(
  name='RemoveGroupMemberPush',
  full_name='pb.RemoveGroupMemberPush',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='opt_id', full_name='pb.RemoveGroupMemberPush.opt_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opt_name', full_name='pb.RemoveGroupMemberPush.opt_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deleted_user_id', full_name='pb.RemoveGroupMemberPush.deleted_user_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=510,
)

_ADDGROUPMEMBERSPUSH.fields_by_name['members'].message_type = logic_dot_ext__pb2._GROUPMEMBER
DESCRIPTOR.message_types_by_name['AddFriendPush'] = _ADDFRIENDPUSH
DESCRIPTOR.message_types_by_name['AgreeAddFriendPush'] = _AGREEADDFRIENDPUSH
DESCRIPTOR.message_types_by_name['UpdateGroupPush'] = _UPDATEGROUPPUSH
DESCRIPTOR.message_types_by_name['AddGroupMembersPush'] = _ADDGROUPMEMBERSPUSH
DESCRIPTOR.message_types_by_name['RemoveGroupMemberPush'] = _REMOVEGROUPMEMBERPUSH
DESCRIPTOR.enum_types_by_name['PushCode'] = _PUSHCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddFriendPush = _reflection.GeneratedProtocolMessageType('AddFriendPush', (_message.Message,), {
  'DESCRIPTOR' : _ADDFRIENDPUSH,
  '__module__' : 'push.ext_pb2'
  # @@protoc_insertion_point(class_scope:pb.AddFriendPush)
  })
_sym_db.RegisterMessage(AddFriendPush)

AgreeAddFriendPush = _reflection.GeneratedProtocolMessageType('AgreeAddFriendPush', (_message.Message,), {
  'DESCRIPTOR' : _AGREEADDFRIENDPUSH,
  '__module__' : 'push.ext_pb2'
  # @@protoc_insertion_point(class_scope:pb.AgreeAddFriendPush)
  })
_sym_db.RegisterMessage(AgreeAddFriendPush)

UpdateGroupPush = _reflection.GeneratedProtocolMessageType('UpdateGroupPush', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEGROUPPUSH,
  '__module__' : 'push.ext_pb2'
  # @@protoc_insertion_point(class_scope:pb.UpdateGroupPush)
  })
_sym_db.RegisterMessage(UpdateGroupPush)

AddGroupMembersPush = _reflection.GeneratedProtocolMessageType('AddGroupMembersPush', (_message.Message,), {
  'DESCRIPTOR' : _ADDGROUPMEMBERSPUSH,
  '__module__' : 'push.ext_pb2'
  # @@protoc_insertion_point(class_scope:pb.AddGroupMembersPush)
  })
_sym_db.RegisterMessage(AddGroupMembersPush)

RemoveGroupMemberPush = _reflection.GeneratedProtocolMessageType('RemoveGroupMemberPush', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEGROUPMEMBERPUSH,
  '__module__' : 'push.ext_pb2'
  # @@protoc_insertion_point(class_scope:pb.RemoveGroupMemberPush)
  })
_sym_db.RegisterMessage(RemoveGroupMemberPush)


# @@protoc_insertion_point(module_scope)
