# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import wpath
from scripts.pb.business import ext_pb2 as business_dot_ext__pb2


class BusinessExtStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignIn = channel.unary_unary(
            "/pb.BusinessExt/SignIn",
            request_serializer=business_dot_ext__pb2.SignInReq.SerializeToString,
            response_deserializer=business_dot_ext__pb2.SignInResp.FromString,
        )
        self.GetUser = channel.unary_unary(
            "/pb.BusinessExt/GetUser",
            request_serializer=business_dot_ext__pb2.GetUserReq.SerializeToString,
            response_deserializer=business_dot_ext__pb2.GetUserResp.FromString,
        )
        self.UpdateUser = channel.unary_unary(
            "/pb.BusinessExt/UpdateUser",
            request_serializer=business_dot_ext__pb2.UpdateUserReq.SerializeToString,
            response_deserializer=business_dot_ext__pb2.UpdateUserResp.FromString,
        )
        self.SearchUser = channel.unary_unary(
            "/pb.BusinessExt/SearchUser",
            request_serializer=business_dot_ext__pb2.SearchUserReq.SerializeToString,
            response_deserializer=business_dot_ext__pb2.SearchUserResp.FromString,
        )


class BusinessExtServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SignIn(self, request, context):
        """登录
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUser(self, request, context):
        """获取用户信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateUser(self, request, context):
        """更新用户信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SearchUser(self, request, context):
        """搜索用户(这里简单数据库实现，生产环境建议使用ES)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BusinessExtServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SignIn": grpc.unary_unary_rpc_method_handler(
            servicer.SignIn,
            request_deserializer=business_dot_ext__pb2.SignInReq.FromString,
            response_serializer=business_dot_ext__pb2.SignInResp.SerializeToString,
        ),
        "GetUser": grpc.unary_unary_rpc_method_handler(
            servicer.GetUser,
            request_deserializer=business_dot_ext__pb2.GetUserReq.FromString,
            response_serializer=business_dot_ext__pb2.GetUserResp.SerializeToString,
        ),
        "UpdateUser": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateUser,
            request_deserializer=business_dot_ext__pb2.UpdateUserReq.FromString,
            response_serializer=business_dot_ext__pb2.UpdateUserResp.SerializeToString,
        ),
        "SearchUser": grpc.unary_unary_rpc_method_handler(
            servicer.SearchUser,
            request_deserializer=business_dot_ext__pb2.SearchUserReq.FromString,
            response_serializer=business_dot_ext__pb2.SearchUserResp.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "pb.BusinessExt", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class BusinessExt(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SignIn(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pb.BusinessExt/SignIn",
            business_dot_ext__pb2.SignInReq.SerializeToString,
            business_dot_ext__pb2.SignInResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pb.BusinessExt/GetUser",
            business_dot_ext__pb2.GetUserReq.SerializeToString,
            business_dot_ext__pb2.GetUserResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UpdateUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pb.BusinessExt/UpdateUser",
            business_dot_ext__pb2.UpdateUserReq.SerializeToString,
            business_dot_ext__pb2.UpdateUserResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SearchUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pb.BusinessExt/SearchUser",
            business_dot_ext__pb2.SearchUserReq.SerializeToString,
            business_dot_ext__pb2.SearchUserResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

